/* StackPDF PDF to Word — stays in this tab. */
function wordUtf8(s){return new TextEncoder().encode(s);}
function wordXml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"");}
function wordPara(t){if(!t)return "<w:p/>";return "<w:p><w:r><w:t xml:space=\"preserve\">"+wordXml(t)+"</w:t></w:r></w:p>";}
function wordBreak(){return "<w:p><w:r><w:br w:type=\"page\"/></w:r></w:p>";}
function wordEmu(w,h){var maxW=5940000,maxH=9360000,cx=Math.round((w||612)*9525),cy=Math.round((h||792)*9525);if(cx>maxW){cy=Math.round(cy*maxW/cx);cx=maxW;}if(cy>maxH){cx=Math.round(cx*maxH/cy);cy=maxH;}return {cx:Math.max(1,cx),cy:Math.max(1,cy)};}
function wordImage(relId,cx,cy,name,id){name=wordXml(name||"image");return "<w:p><w:r><w:drawing><wp:inline distT=\"0\" distB=\"0\" distL=\"0\" distR=\"0\"><wp:extent cx=\""+cx+"\" cy=\""+cy+"\"/><wp:docPr id=\""+id+"\" name=\""+name+"\"/><wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect=\"1\"/></wp:cNvGraphicFramePr><a:graphic><a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:pic><pic:nvPicPr><pic:cNvPr id=\"0\" name=\""+name+"\"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed=\""+relId+"\"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\""+cx+"\" cy=\""+cy+"\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>";}
function joinLine(parts){var s="";for(var i=0;i<parts.length;i++){var t=parts[i];if(!t)continue;if(!s)s=t;else if(/\s$/.test(s)||/^\s/.test(t))s+=t;else s+=" "+t;}return s.replace(/[ \t]+/g," ").trim();}
function textItemsToLines(items){if(!items||!items.length)return [];var rows=[];for(var i=0;i<items.length;i++){var it=items[i];var str=it.str||"";if(!str&&!it.hasEOL)continue;var tr=it.transform||[1,0,0,1,0,0];var x=tr[4],y=tr[5],h=Math.abs(tr[3]||it.height||10)||10;var row=null,tol=Math.max(2,h*0.35);for(var r=0;r<rows.length;r++){if(Math.abs(rows[r].y-y)<=tol){row=rows[r];break;}}if(!row){row={y:y,parts:[]};rows.push(row);}if(str)row.parts.push({x:x,str:str});}rows.sort(function(a,b){return b.y-a.y;});return rows.map(function(row){row.parts.sort(function(a,b){return a.x-b.x;});return joinLine(row.parts.map(function(p){return p.str;}));}).filter(Boolean);}
function buildDocx(pages){var body=[],rels=[],media=[],imgN=0,hasPng=false,i,p,L,wrote,rid,fname,size;
for(i=0;i<pages.length;i++){if(i)body.push(wordBreak());p=pages[i]||{};wrote=false;if(p.lines&&p.lines.length){for(L=0;L<p.lines.length;L++)body.push(wordPara(p.lines[L]));wrote=true;}if(!wrote&&p.image){imgN++;hasPng=true;rid="rId"+imgN;fname="image"+imgN+".png";size=wordEmu(p.imageWidth,p.imageHeight);body.push(wordImage(rid,size.cx,size.cy,fname,imgN));rels.push("<Relationship Id=\""+rid+"\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image\" Target=\"media/"+fname+"\"/>");media.push({name:"word/media/"+fname,data:p.image});wrote=true;}if(!wrote)body.push("<w:p/>");}
body.push("<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/><w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/></w:sectPr>");
var documentXml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\" xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><w:body>"+body.join("")+"</w:body></w:document>";
var types="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/>"+(hasPng?"<Default Extension=\"png\" ContentType=\"image/png\"/>":"")+"<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/></Types>";
var rootRels="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/></Relationships>";
var docRels="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"+rels.join("")+"</Relationships>";
var zip=typeof zipStore==="function"?zipStore:(typeof StackPDF!=="undefined"?StackPDF.zipStore:null);
if(!zip)throw new Error("zipStore is missing.");
return zip([{name:"[Content_Types].xml",data:wordUtf8(types)},{name:"_rels/.rels",data:wordUtf8(rootRels)},{name:"word/document.xml",data:wordUtf8(documentXml)},{name:"word/_rels/document.xml.rels",data:wordUtf8(docRels)}].concat(media));}
function pdfjsApi(){var L=(typeof pdfjsLib!=="undefined")?pdfjsLib:(typeof window!=="undefined"?window.pdfjsLib:null);if(!L||!L.getDocument)throw new Error("pdf.js failed to load.");return L;}
function ensurePdfjsWorker(){var L=pdfjsApi();if(L.GlobalWorkerOptions&&!L.GlobalWorkerOptions.workerSrc){L.GlobalWorkerOptions.workerSrc=new URL("vendor/pdfjs/pdf.worker.min.js", (typeof document!=="undefined"&&document.baseURI)||"./").href;}}
function significantText(lines){var s=(lines||[]).join("");return s.replace(/\s+/g,"").length>=8;}
function dataUrlToBytes(url){var m=String(url).match(/^data:[^;]+;base64,(.+)$/);if(!m)return null;var bin=typeof atob==="function"?atob(m[1]):Buffer.from(m[1],"base64").toString("binary");var out=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
async function canvasToPng(canvas){if(canvas.toBlob){var blob=await new Promise(function(res){canvas.toBlob(res,"image/png");});if(blob){var buf=await blob.arrayBuffer();return new Uint8Array(buf);}}return dataUrlToBytes(canvas.toDataURL("image/png"));}
async function rasterPdfPage(page){if(typeof document==="undefined")return null;try{var base=page.getViewport({scale:1});var pixels=Math.max(1,base.width*base.height);var scale=1.5;if(pixels*scale*scale>2500000)scale=Math.sqrt(2500000/pixels);if(scale<0.55)scale=0.55;var vp=page.getViewport({scale:scale});var canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(vp.width));canvas.height=Math.max(1,Math.round(vp.height));var ctx=canvas.getContext("2d",{alpha:false});if(!ctx)return null;ctx.fillStyle="#ffffff";ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:vp,intent:"display"}).promise;var data=await canvasToPng(canvas);if(!data||!data.length)return null;return {data:data,width:canvas.width,height:canvas.height};}catch(e){return null;}}
async function pdfToDocx(bytes,pages1,onProgress){ensurePdfjsWorker();var api=pdfjsApi();var copy=bytes&&bytes.slice?bytes.slice():new Uint8Array(bytes);var task=api.getDocument({data:copy,password:"",verbosity:0,isEvalSupported:false,disableAutoFetch:true,disableRange:true,disableStream:true,useWorkerFetch:false,stopAtErrors:false});task.onPassword=function(){throw new Error("This PDF is password-protected.");};var doc=null;try{doc=await task.promise;var n=doc.numPages;if(!n)throw new Error("This PDF has no pages.");var want=pages1&&pages1.length?pages1.slice():[];if(!want.length){for(var i=1;i<=n;i++)want.push(i);}var pages=[],gotText=false,gotImage=false;for(var p=0;p<want.length;p++){var num=want[p];if(!Number.isInteger(num)||num<1||num>n)throw new Error("Page "+num+" is out of range (1-"+n+").");if(onProgress)onProgress({phase:"word",done:p,total:want.length});var page=await doc.getPage(num);var content=await page.getTextContent({disableNormalization:false});var lines=textItemsToLines(content.items||[]);var image=null;if(!significantText(lines)){var rast=await rasterPdfPage(page);if(rast){image=rast;lines=[];}}if(lines.length)gotText=true;if(image)gotImage=true;pages.push({lines:lines,image:image?image.data:null,imageWidth:image?image.width:0,imageHeight:image?image.height:0});if(typeof yieldToMain==="function")await yieldToMain();else await new Promise(function(r){setTimeout(r,0);});}
if(!gotText&&!gotImage)throw new Error("No text could be extracted from this PDF.");if(onProgress)onProgress({phase:"docx",done:want.length,total:want.length});return buildDocx(pages);}catch(err){var msg=err&&err.message?String(err.message):"";var name=err&&err.name?String(err.name):"";if(name==="PasswordException"||/password/i.test(msg)||/encrypt/i.test(msg)){var e=new Error("This PDF is password-protected.");e.name="PasswordException";throw e;}if(name==="InvalidPDFException"||name==="MissingPDFException"){var d=new Error("This PDF is damaged or unreadable.");d.name=name;throw d;}throw err;}finally{try{if(doc)await doc.destroy();else if(task&&task.destroy)await task.destroy();}catch(x){}}}
if(typeof StackPDF!=="undefined"){StackPDF.pdfToDocx=pdfToDocx;StackPDF.buildDocx=buildDocx;StackPDF.textItemsToLines=textItemsToLines;}if(typeof module!=="undefined"&&module.exports){module.exports.pdfToDocx=pdfToDocx;module.exports.buildDocx=buildDocx;module.exports.textItemsToLines=textItemsToLines;}
if(typeof document!=="undefined"){try{ensurePdfjsWorker();}catch(e){}}
